# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: CI
# env:
#   API_KEY: ${{ secrets.API_KEY }}

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: Install dependencies
      # Using npm ci is generally faster than running npm i because it caches dependencies
      run: |
        cd my-react-app-1
        npm ci
    - name: Build the app
      run: |
        cd my-react-app-1
        npm run build
    - name: Run component tests
      run: |
        cd my-react-app-1
        npm run test
    - name: Start the app
      # Wait 60 seconds until starts before giving an error
      run: |
        cd my-react-app-1
        npm start &
        npx wait-on --timeout 60000
